/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyAnswersRouteImport } from './routes/my-answers'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as BuyerInboxRouteImport } from './routes/buyer-inbox'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntakeIndexRouteImport } from './routes/intake.index'
import { Route as RfpRfpIdRouteImport } from './routes/rfp.$rfpId'
import { Route as IntakeThankYouRouteImport } from './routes/intake.thank-you'
import { Route as IntakeTechnologyRouteImport } from './routes/intake.technology'
import { Route as IntakeTechReplaceRouteImport } from './routes/intake.tech-replace'
import { Route as IntakeTechNewRouteImport } from './routes/intake.tech-new'
import { Route as IntakeLawfirmRouteImport } from './routes/intake.lawfirm'
import { Route as IntakeAlspRouteImport } from './routes/intake.alsp'
import { Route as BuyerRfpRfpIdRouteImport } from './routes/buyer-rfp.$rfpId'
import { Route as RfpRfpIdIndexRouteImport } from './routes/rfp.$rfpId.index'
import { Route as BuyerRfpRfpIdIndexRouteImport } from './routes/buyer-rfp.$rfpId.index'
import { Route as RfpRfpIdQuestionsRouteImport } from './routes/rfp.$rfpId.questions'
import { Route as RfpRfpIdDocumentsRouteImport } from './routes/rfp.$rfpId.documents'
import { Route as IntakeLegalServicesNeedRouteImport } from './routes/intake.legal-services.need'
import { Route as IntakeLegalServicesDeliveryRouteImport } from './routes/intake.legal-services.delivery'
import { Route as BuyerRfpRfpIdResponsesRouteImport } from './routes/buyer-rfp.$rfpId.responses'
import { Route as BuyerRfpRfpIdDocumentsRouteImport } from './routes/buyer-rfp.$rfpId.documents'
import { Route as BuyerRfpRfpIdCompareRouteImport } from './routes/buyer-rfp.$rfpId.compare'
import { Route as BuyerRfpRfpIdAnalyticsRouteImport } from './routes/buyer-rfp.$rfpId.analytics'

const MyAnswersRoute = MyAnswersRouteImport.update({
  id: '/my-answers',
  path: '/my-answers',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerInboxRoute = BuyerInboxRouteImport.update({
  id: '/buyer-inbox',
  path: '/buyer-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntakeRoute,
} as any)
const RfpRfpIdRoute = RfpRfpIdRouteImport.update({
  id: '/rfp/$rfpId',
  path: '/rfp/$rfpId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeThankYouRoute = IntakeThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => IntakeRoute,
} as any)
const IntakeTechnologyRoute = IntakeTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => IntakeRoute,
} as any)
const IntakeTechReplaceRoute = IntakeTechReplaceRouteImport.update({
  id: '/tech-replace',
  path: '/tech-replace',
  getParentRoute: () => IntakeRoute,
} as any)
const IntakeTechNewRoute = IntakeTechNewRouteImport.update({
  id: '/tech-new',
  path: '/tech-new',
  getParentRoute: () => IntakeRoute,
} as any)
const IntakeLawfirmRoute = IntakeLawfirmRouteImport.update({
  id: '/lawfirm',
  path: '/lawfirm',
  getParentRoute: () => IntakeRoute,
} as any)
const IntakeAlspRoute = IntakeAlspRouteImport.update({
  id: '/alsp',
  path: '/alsp',
  getParentRoute: () => IntakeRoute,
} as any)
const BuyerRfpRfpIdRoute = BuyerRfpRfpIdRouteImport.update({
  id: '/buyer-rfp/$rfpId',
  path: '/buyer-rfp/$rfpId',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpRfpIdIndexRoute = RfpRfpIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RfpRfpIdRoute,
} as any)
const BuyerRfpRfpIdIndexRoute = BuyerRfpRfpIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerRfpRfpIdRoute,
} as any)
const RfpRfpIdQuestionsRoute = RfpRfpIdQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => RfpRfpIdRoute,
} as any)
const RfpRfpIdDocumentsRoute = RfpRfpIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => RfpRfpIdRoute,
} as any)
const IntakeLegalServicesNeedRoute = IntakeLegalServicesNeedRouteImport.update({
  id: '/legal-services/need',
  path: '/legal-services/need',
  getParentRoute: () => IntakeRoute,
} as any)
const IntakeLegalServicesDeliveryRoute =
  IntakeLegalServicesDeliveryRouteImport.update({
    id: '/legal-services/delivery',
    path: '/legal-services/delivery',
    getParentRoute: () => IntakeRoute,
  } as any)
const BuyerRfpRfpIdResponsesRoute = BuyerRfpRfpIdResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => BuyerRfpRfpIdRoute,
} as any)
const BuyerRfpRfpIdDocumentsRoute = BuyerRfpRfpIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => BuyerRfpRfpIdRoute,
} as any)
const BuyerRfpRfpIdCompareRoute = BuyerRfpRfpIdCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => BuyerRfpRfpIdRoute,
} as any)
const BuyerRfpRfpIdAnalyticsRoute = BuyerRfpRfpIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BuyerRfpRfpIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyer-inbox': typeof BuyerInboxRoute
  '/intake': typeof IntakeRouteWithChildren
  '/my-answers': typeof MyAnswersRoute
  '/buyer-rfp/$rfpId': typeof BuyerRfpRfpIdRouteWithChildren
  '/intake/alsp': typeof IntakeAlspRoute
  '/intake/lawfirm': typeof IntakeLawfirmRoute
  '/intake/tech-new': typeof IntakeTechNewRoute
  '/intake/tech-replace': typeof IntakeTechReplaceRoute
  '/intake/technology': typeof IntakeTechnologyRoute
  '/intake/thank-you': typeof IntakeThankYouRoute
  '/rfp/$rfpId': typeof RfpRfpIdRouteWithChildren
  '/intake/': typeof IntakeIndexRoute
  '/buyer-rfp/$rfpId/analytics': typeof BuyerRfpRfpIdAnalyticsRoute
  '/buyer-rfp/$rfpId/compare': typeof BuyerRfpRfpIdCompareRoute
  '/buyer-rfp/$rfpId/documents': typeof BuyerRfpRfpIdDocumentsRoute
  '/buyer-rfp/$rfpId/responses': typeof BuyerRfpRfpIdResponsesRoute
  '/intake/legal-services/delivery': typeof IntakeLegalServicesDeliveryRoute
  '/intake/legal-services/need': typeof IntakeLegalServicesNeedRoute
  '/rfp/$rfpId/documents': typeof RfpRfpIdDocumentsRoute
  '/rfp/$rfpId/questions': typeof RfpRfpIdQuestionsRoute
  '/buyer-rfp/$rfpId/': typeof BuyerRfpRfpIdIndexRoute
  '/rfp/$rfpId/': typeof RfpRfpIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyer-inbox': typeof BuyerInboxRoute
  '/my-answers': typeof MyAnswersRoute
  '/intake/alsp': typeof IntakeAlspRoute
  '/intake/lawfirm': typeof IntakeLawfirmRoute
  '/intake/tech-new': typeof IntakeTechNewRoute
  '/intake/tech-replace': typeof IntakeTechReplaceRoute
  '/intake/technology': typeof IntakeTechnologyRoute
  '/intake/thank-you': typeof IntakeThankYouRoute
  '/intake': typeof IntakeIndexRoute
  '/buyer-rfp/$rfpId/analytics': typeof BuyerRfpRfpIdAnalyticsRoute
  '/buyer-rfp/$rfpId/compare': typeof BuyerRfpRfpIdCompareRoute
  '/buyer-rfp/$rfpId/documents': typeof BuyerRfpRfpIdDocumentsRoute
  '/buyer-rfp/$rfpId/responses': typeof BuyerRfpRfpIdResponsesRoute
  '/intake/legal-services/delivery': typeof IntakeLegalServicesDeliveryRoute
  '/intake/legal-services/need': typeof IntakeLegalServicesNeedRoute
  '/rfp/$rfpId/documents': typeof RfpRfpIdDocumentsRoute
  '/rfp/$rfpId/questions': typeof RfpRfpIdQuestionsRoute
  '/buyer-rfp/$rfpId': typeof BuyerRfpRfpIdIndexRoute
  '/rfp/$rfpId': typeof RfpRfpIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyer-inbox': typeof BuyerInboxRoute
  '/intake': typeof IntakeRouteWithChildren
  '/my-answers': typeof MyAnswersRoute
  '/buyer-rfp/$rfpId': typeof BuyerRfpRfpIdRouteWithChildren
  '/intake/alsp': typeof IntakeAlspRoute
  '/intake/lawfirm': typeof IntakeLawfirmRoute
  '/intake/tech-new': typeof IntakeTechNewRoute
  '/intake/tech-replace': typeof IntakeTechReplaceRoute
  '/intake/technology': typeof IntakeTechnologyRoute
  '/intake/thank-you': typeof IntakeThankYouRoute
  '/rfp/$rfpId': typeof RfpRfpIdRouteWithChildren
  '/intake/': typeof IntakeIndexRoute
  '/buyer-rfp/$rfpId/analytics': typeof BuyerRfpRfpIdAnalyticsRoute
  '/buyer-rfp/$rfpId/compare': typeof BuyerRfpRfpIdCompareRoute
  '/buyer-rfp/$rfpId/documents': typeof BuyerRfpRfpIdDocumentsRoute
  '/buyer-rfp/$rfpId/responses': typeof BuyerRfpRfpIdResponsesRoute
  '/intake/legal-services/delivery': typeof IntakeLegalServicesDeliveryRoute
  '/intake/legal-services/need': typeof IntakeLegalServicesNeedRoute
  '/rfp/$rfpId/documents': typeof RfpRfpIdDocumentsRoute
  '/rfp/$rfpId/questions': typeof RfpRfpIdQuestionsRoute
  '/buyer-rfp/$rfpId/': typeof BuyerRfpRfpIdIndexRoute
  '/rfp/$rfpId/': typeof RfpRfpIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyer-inbox'
    | '/intake'
    | '/my-answers'
    | '/buyer-rfp/$rfpId'
    | '/intake/alsp'
    | '/intake/lawfirm'
    | '/intake/tech-new'
    | '/intake/tech-replace'
    | '/intake/technology'
    | '/intake/thank-you'
    | '/rfp/$rfpId'
    | '/intake/'
    | '/buyer-rfp/$rfpId/analytics'
    | '/buyer-rfp/$rfpId/compare'
    | '/buyer-rfp/$rfpId/documents'
    | '/buyer-rfp/$rfpId/responses'
    | '/intake/legal-services/delivery'
    | '/intake/legal-services/need'
    | '/rfp/$rfpId/documents'
    | '/rfp/$rfpId/questions'
    | '/buyer-rfp/$rfpId/'
    | '/rfp/$rfpId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyer-inbox'
    | '/my-answers'
    | '/intake/alsp'
    | '/intake/lawfirm'
    | '/intake/tech-new'
    | '/intake/tech-replace'
    | '/intake/technology'
    | '/intake/thank-you'
    | '/intake'
    | '/buyer-rfp/$rfpId/analytics'
    | '/buyer-rfp/$rfpId/compare'
    | '/buyer-rfp/$rfpId/documents'
    | '/buyer-rfp/$rfpId/responses'
    | '/intake/legal-services/delivery'
    | '/intake/legal-services/need'
    | '/rfp/$rfpId/documents'
    | '/rfp/$rfpId/questions'
    | '/buyer-rfp/$rfpId'
    | '/rfp/$rfpId'
  id:
    | '__root__'
    | '/'
    | '/buyer-inbox'
    | '/intake'
    | '/my-answers'
    | '/buyer-rfp/$rfpId'
    | '/intake/alsp'
    | '/intake/lawfirm'
    | '/intake/tech-new'
    | '/intake/tech-replace'
    | '/intake/technology'
    | '/intake/thank-you'
    | '/rfp/$rfpId'
    | '/intake/'
    | '/buyer-rfp/$rfpId/analytics'
    | '/buyer-rfp/$rfpId/compare'
    | '/buyer-rfp/$rfpId/documents'
    | '/buyer-rfp/$rfpId/responses'
    | '/intake/legal-services/delivery'
    | '/intake/legal-services/need'
    | '/rfp/$rfpId/documents'
    | '/rfp/$rfpId/questions'
    | '/buyer-rfp/$rfpId/'
    | '/rfp/$rfpId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerInboxRoute: typeof BuyerInboxRoute
  IntakeRoute: typeof IntakeRouteWithChildren
  MyAnswersRoute: typeof MyAnswersRoute
  BuyerRfpRfpIdRoute: typeof BuyerRfpRfpIdRouteWithChildren
  RfpRfpIdRoute: typeof RfpRfpIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-answers': {
      id: '/my-answers'
      path: '/my-answers'
      fullPath: '/my-answers'
      preLoaderRoute: typeof MyAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-inbox': {
      id: '/buyer-inbox'
      path: '/buyer-inbox'
      fullPath: '/buyer-inbox'
      preLoaderRoute: typeof BuyerInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/rfp/$rfpId': {
      id: '/rfp/$rfpId'
      path: '/rfp/$rfpId'
      fullPath: '/rfp/$rfpId'
      preLoaderRoute: typeof RfpRfpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/thank-you': {
      id: '/intake/thank-you'
      path: '/thank-you'
      fullPath: '/intake/thank-you'
      preLoaderRoute: typeof IntakeThankYouRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/intake/technology': {
      id: '/intake/technology'
      path: '/technology'
      fullPath: '/intake/technology'
      preLoaderRoute: typeof IntakeTechnologyRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/intake/tech-replace': {
      id: '/intake/tech-replace'
      path: '/tech-replace'
      fullPath: '/intake/tech-replace'
      preLoaderRoute: typeof IntakeTechReplaceRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/intake/tech-new': {
      id: '/intake/tech-new'
      path: '/tech-new'
      fullPath: '/intake/tech-new'
      preLoaderRoute: typeof IntakeTechNewRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/intake/lawfirm': {
      id: '/intake/lawfirm'
      path: '/lawfirm'
      fullPath: '/intake/lawfirm'
      preLoaderRoute: typeof IntakeLawfirmRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/intake/alsp': {
      id: '/intake/alsp'
      path: '/alsp'
      fullPath: '/intake/alsp'
      preLoaderRoute: typeof IntakeAlspRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/buyer-rfp/$rfpId': {
      id: '/buyer-rfp/$rfpId'
      path: '/buyer-rfp/$rfpId'
      fullPath: '/buyer-rfp/$rfpId'
      preLoaderRoute: typeof BuyerRfpRfpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfp/$rfpId/': {
      id: '/rfp/$rfpId/'
      path: '/'
      fullPath: '/rfp/$rfpId/'
      preLoaderRoute: typeof RfpRfpIdIndexRouteImport
      parentRoute: typeof RfpRfpIdRoute
    }
    '/buyer-rfp/$rfpId/': {
      id: '/buyer-rfp/$rfpId/'
      path: '/'
      fullPath: '/buyer-rfp/$rfpId/'
      preLoaderRoute: typeof BuyerRfpRfpIdIndexRouteImport
      parentRoute: typeof BuyerRfpRfpIdRoute
    }
    '/rfp/$rfpId/questions': {
      id: '/rfp/$rfpId/questions'
      path: '/questions'
      fullPath: '/rfp/$rfpId/questions'
      preLoaderRoute: typeof RfpRfpIdQuestionsRouteImport
      parentRoute: typeof RfpRfpIdRoute
    }
    '/rfp/$rfpId/documents': {
      id: '/rfp/$rfpId/documents'
      path: '/documents'
      fullPath: '/rfp/$rfpId/documents'
      preLoaderRoute: typeof RfpRfpIdDocumentsRouteImport
      parentRoute: typeof RfpRfpIdRoute
    }
    '/intake/legal-services/need': {
      id: '/intake/legal-services/need'
      path: '/legal-services/need'
      fullPath: '/intake/legal-services/need'
      preLoaderRoute: typeof IntakeLegalServicesNeedRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/intake/legal-services/delivery': {
      id: '/intake/legal-services/delivery'
      path: '/legal-services/delivery'
      fullPath: '/intake/legal-services/delivery'
      preLoaderRoute: typeof IntakeLegalServicesDeliveryRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/buyer-rfp/$rfpId/responses': {
      id: '/buyer-rfp/$rfpId/responses'
      path: '/responses'
      fullPath: '/buyer-rfp/$rfpId/responses'
      preLoaderRoute: typeof BuyerRfpRfpIdResponsesRouteImport
      parentRoute: typeof BuyerRfpRfpIdRoute
    }
    '/buyer-rfp/$rfpId/documents': {
      id: '/buyer-rfp/$rfpId/documents'
      path: '/documents'
      fullPath: '/buyer-rfp/$rfpId/documents'
      preLoaderRoute: typeof BuyerRfpRfpIdDocumentsRouteImport
      parentRoute: typeof BuyerRfpRfpIdRoute
    }
    '/buyer-rfp/$rfpId/compare': {
      id: '/buyer-rfp/$rfpId/compare'
      path: '/compare'
      fullPath: '/buyer-rfp/$rfpId/compare'
      preLoaderRoute: typeof BuyerRfpRfpIdCompareRouteImport
      parentRoute: typeof BuyerRfpRfpIdRoute
    }
    '/buyer-rfp/$rfpId/analytics': {
      id: '/buyer-rfp/$rfpId/analytics'
      path: '/analytics'
      fullPath: '/buyer-rfp/$rfpId/analytics'
      preLoaderRoute: typeof BuyerRfpRfpIdAnalyticsRouteImport
      parentRoute: typeof BuyerRfpRfpIdRoute
    }
  }
}

interface IntakeRouteChildren {
  IntakeAlspRoute: typeof IntakeAlspRoute
  IntakeLawfirmRoute: typeof IntakeLawfirmRoute
  IntakeTechNewRoute: typeof IntakeTechNewRoute
  IntakeTechReplaceRoute: typeof IntakeTechReplaceRoute
  IntakeTechnologyRoute: typeof IntakeTechnologyRoute
  IntakeThankYouRoute: typeof IntakeThankYouRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
  IntakeLegalServicesDeliveryRoute: typeof IntakeLegalServicesDeliveryRoute
  IntakeLegalServicesNeedRoute: typeof IntakeLegalServicesNeedRoute
}

const IntakeRouteChildren: IntakeRouteChildren = {
  IntakeAlspRoute: IntakeAlspRoute,
  IntakeLawfirmRoute: IntakeLawfirmRoute,
  IntakeTechNewRoute: IntakeTechNewRoute,
  IntakeTechReplaceRoute: IntakeTechReplaceRoute,
  IntakeTechnologyRoute: IntakeTechnologyRoute,
  IntakeThankYouRoute: IntakeThankYouRoute,
  IntakeIndexRoute: IntakeIndexRoute,
  IntakeLegalServicesDeliveryRoute: IntakeLegalServicesDeliveryRoute,
  IntakeLegalServicesNeedRoute: IntakeLegalServicesNeedRoute,
}

const IntakeRouteWithChildren =
  IntakeRoute._addFileChildren(IntakeRouteChildren)

interface BuyerRfpRfpIdRouteChildren {
  BuyerRfpRfpIdAnalyticsRoute: typeof BuyerRfpRfpIdAnalyticsRoute
  BuyerRfpRfpIdCompareRoute: typeof BuyerRfpRfpIdCompareRoute
  BuyerRfpRfpIdDocumentsRoute: typeof BuyerRfpRfpIdDocumentsRoute
  BuyerRfpRfpIdResponsesRoute: typeof BuyerRfpRfpIdResponsesRoute
  BuyerRfpRfpIdIndexRoute: typeof BuyerRfpRfpIdIndexRoute
}

const BuyerRfpRfpIdRouteChildren: BuyerRfpRfpIdRouteChildren = {
  BuyerRfpRfpIdAnalyticsRoute: BuyerRfpRfpIdAnalyticsRoute,
  BuyerRfpRfpIdCompareRoute: BuyerRfpRfpIdCompareRoute,
  BuyerRfpRfpIdDocumentsRoute: BuyerRfpRfpIdDocumentsRoute,
  BuyerRfpRfpIdResponsesRoute: BuyerRfpRfpIdResponsesRoute,
  BuyerRfpRfpIdIndexRoute: BuyerRfpRfpIdIndexRoute,
}

const BuyerRfpRfpIdRouteWithChildren = BuyerRfpRfpIdRoute._addFileChildren(
  BuyerRfpRfpIdRouteChildren,
)

interface RfpRfpIdRouteChildren {
  RfpRfpIdDocumentsRoute: typeof RfpRfpIdDocumentsRoute
  RfpRfpIdQuestionsRoute: typeof RfpRfpIdQuestionsRoute
  RfpRfpIdIndexRoute: typeof RfpRfpIdIndexRoute
}

const RfpRfpIdRouteChildren: RfpRfpIdRouteChildren = {
  RfpRfpIdDocumentsRoute: RfpRfpIdDocumentsRoute,
  RfpRfpIdQuestionsRoute: RfpRfpIdQuestionsRoute,
  RfpRfpIdIndexRoute: RfpRfpIdIndexRoute,
}

const RfpRfpIdRouteWithChildren = RfpRfpIdRoute._addFileChildren(
  RfpRfpIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerInboxRoute: BuyerInboxRoute,
  IntakeRoute: IntakeRouteWithChildren,
  MyAnswersRoute: MyAnswersRoute,
  BuyerRfpRfpIdRoute: BuyerRfpRfpIdRouteWithChildren,
  RfpRfpIdRoute: RfpRfpIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
