/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RfpRfpIdRouteImport } from './routes/rfp.$rfpId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpRfpIdRoute = RfpRfpIdRouteImport.update({
  id: '/rfp/$rfpId',
  path: '/rfp/$rfpId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rfp/$rfpId': typeof RfpRfpIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rfp/$rfpId': typeof RfpRfpIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rfp/$rfpId': typeof RfpRfpIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rfp/$rfpId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rfp/$rfpId'
  id: '__root__' | '/' | '/rfp/$rfpId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RfpRfpIdRoute: typeof RfpRfpIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfp/$rfpId': {
      id: '/rfp/$rfpId'
      path: '/rfp/$rfpId'
      fullPath: '/rfp/$rfpId'
      preLoaderRoute: typeof RfpRfpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RfpRfpIdRoute: RfpRfpIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
